from typing import Protocol, TypeVar

_T = TypeVar("_T")


class RepositoryProtocol(Protocol[_T]):
    """Base CRUD repository interface"""

    async def create(self, obj: _T) -> _T: ...
    async def read(self, obj: _T) -> _T: ...
    async def update(self, obj: _T) -> _T: ...
    async def delete(self, obj: _T) -> _T: ...


class RedisRepositoryProtocol(RepositoryProtocol[_T]): ...
