x-default: &default
  restart: unless-stopped
  networks:
  - graduate-work
  env_file:
  - .env
  depends_on:
    python_base:
      condition: service_completed_successfully

x-logging: &logging
  logging:
    driver: gelf
    options:
      gelf-address: udp://127.0.0.1:5044
      tag: auth

services:
  auth_app_postgres:
    <<: *default
    image: postgres:15
    expose:
    - ${POSTGRES_PORT}
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
    - pg_prod_auth_data:/var/lib/postgresql/data

  auth_app_redis:
    <<: *default
    image: redis:7.2.4
    expose:
    - ${REDIS_PORT}

  auth_app_backend:
    <<: [*default, *logging]
    build:
      context: .
    expose:
    - ${API_PORT}
    ports:
    - ${API_PORT}:${API_PORT}

  auth_app_jaeger:
    <<: *default
    image: jaegertracing/all-in-one:1.20.0
    container_name: jaeger
    ports:
    - 6831:6831/udp
    - 16686:16686
    environment:
    - GOMAXPROCS=2

volumes:
  pg_prod_auth_data:

networks:
  graduate-work:
    name: graduate-work
