repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: no-commit-to-branch

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --indent, '2', --inline-comment-spaces, '2', --trailing-commas]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.5
  hooks:
  - id: ruff-format
    args: [--config=pyproject.toml]
  - id: ruff
    args: [--config=pyproject.toml, --fix, --exit-non-zero-on-fix]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
    args: [--config-file=pyproject.toml, --install-types, --non-interactive]
    additional_dependencies:
    - pydantic
