services:

  app:
    build:
      context: ..
      dockerfile: deploy-test-integration/Dockerfile.app
    env_file:
      - .env
    expose:
      - ${APP_PORT}

  tests:
    build:
      context: ..
      dockerfile: deploy-test-integration/Dockerfile.tests
    env_file:
      - .env
    depends_on:
      - app