"""table User deleted

Revision ID: e981b4a2272f
Revises: 6bfae7d1d1b9
Create Date: 2024-09-02 20:23:44.427064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e981b4a2272f"
down_revision: Union[str, None] = "6bfae7d1d1b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user')
    op.execute('DROP TABLE "user" CASCADE')
    op.create_unique_constraint(None, "order", ["id"])
    # op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_unique_constraint(None, "order_product", ["id"])
    op.create_unique_constraint(None, "payment_method", ["id"])
    # op.drop_constraint('payment_method_user_id_fkey', 'payment_method', type_='foreignkey')
    op.alter_column("product", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.create_unique_constraint(None, "product", ["id"])
    op.create_unique_constraint(None, "transaction", ["id"])
    op.create_unique_constraint(None, "user_product", ["id"])
    # op.drop_constraint('user_product_user_id_fkey', 'user_product', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("user_product_user_id_fkey", "user_product", "user", ["user_id"], ["id"])
    op.drop_constraint(None, "user_product", type_="unique")
    op.drop_constraint(None, "transaction", type_="unique")
    op.drop_constraint(None, "product", type_="unique")
    op.alter_column("product", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.create_foreign_key("payment_method_user_id_fkey", "payment_method", "user", ["user_id"], ["id"])
    op.drop_constraint(None, "payment_method", type_="unique")
    op.drop_constraint(None, "order_product", type_="unique")
    op.create_foreign_key("order_user_id_fkey", "order", "user", ["user_id"], ["id"])
    op.drop_constraint(None, "order", type_="unique")
    op.create_table(
        "user",
        sa.Column("sso_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("closed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint("email", name="user_email_key"),
        sa.UniqueConstraint("sso_id", name="user_sso_id_key"),
    )
    # ### end Alembic commands ###
