"""Add external_id for transaction

Revision ID: 69fde69db77b
Revises: e981b4a2272f
Create Date: 2024-09-15 22:49:46.846289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69fde69db77b"
down_revision: Union[str, None] = "e981b4a2272f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("external_id", sa.String(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "external_id")
    # ### end Alembic commands ###
