services:

  billing_app_backend:
    build:
      context: ..
      dockerfile: deploy-app/Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}