"""add login history

Revision ID: e7acc41ca701
Revises: 942536863bc1
Create Date: 2024-06-27 16:24:50.314045

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "e7acc41ca701"
down_revision: Union[str, None] = "942536863bc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def create_partition_login_history() -> None:
    """
    Creating partition by day of week of timestamp
    """
    for day in range(0, 7):
        op.execute(
            text(
                f"""
                CREATE TABLE IF NOT EXISTS "login_history_{day}"
                PARTITION OF login_history_parent
                FOR VALUES IN ({day})"""
            )
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_history_parent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=15), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "weekday"),
        sa.UniqueConstraint("id", "weekday"),
        postgresql_partition_by="LIST (weekday)",
    )

    create_partition_login_history()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for day in range(0, 7):
        op.drop_table(f"login_history_{day}")
    op.drop_table("login_history_parent")
    # ### end Alembic commands ###
