"""add social networks

Revision ID: 9a394f38538e
Revises: e7acc41ca701
Create Date: 2024-06-27 17:28:00.410537

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a394f38538e"
down_revision: Union[str, None] = "e7acc41ca701"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_networks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("social_network_id", sa.String(), nullable=False),
        sa.Column("social_network_email", sa.String(), nullable=False),
        sa.Column(
            "social_networks_name", sa.Enum("yandex", "vk", "google", name="socialnetworksnames"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("social_networks")
    # ### end Alembic commands ###
