@startuml
skinparam linetype ortho
skinparam componentStyle rectangle
skinparam componentSpacing 60
skinparam nodeSpacing 60
skinparam groupInheritancePadding 25
left to right direction

actor "User" as user

[Frontend] as frontend



[Auth API] as auth
collections "Payment Providers" as payment_providers


rectangle "Billing Service" as billing {
      [Billing API] as api


    rectangle "Database Layer" as data {
        database "Postgres" as db
        database "Redis Cache" as cache
    }

    collections "Workers layer" as worker


    queue "Event Bus (Kafka)" as kafka
}

rectangle "Support Services" as support {
    [Logging Service]
    [Notification Service]
}

user --> frontend
frontend --> billing
api --> kafka
api --> data
data --> api
kafka --> worker
worker --> kafka
worker --> data
worker --> payment_providers
billing --> support
billing --> auth
@enduml
