x-default: &default
  restart: unless-stopped
  networks:
  - graduate-work
  env_file:
  - .env
  depends_on:
    python_base:
      condition: service_completed_successfully

services:
  billing_app_backend:
    <<: *default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - ${APP_PORT}:${APP_PORT}
    expose:
    - ${APP_PORT}

  billing_app_postgres:
    <<: *default
    image: postgres:15
    expose:
    - ${PG_PORT}
    ports:
    - ${PG_PORT}:${PG_PORT}
    volumes:
    - pg_prod_billing_data:/var/lib/postgresql/data

volumes:
  pg_prod_billing_data:

networks:
  graduate-work:
    name: graduate-work
